corporate:
  social_media:
    facebook: 'https://www.facebook.com/'
    instagram: 'https://www.instagram.com/'
    x: 'https://twitter.com/'
    tiktok: 'https://www.tiktok.com/'
  pages:
    footerPid: 6
    logo: '/'