settings:
  corporate.logo:
    label: 'Logo Url'
    description: 'URL of the image to be used as logo'
    type: string
    default: ''
  corporate.logoSmall:
    label: 'Logo Url'
    description: 'URL of the image to be used as logo on scroll'
    type: string
    default: ''
  corporate.styles.colors.primary:
    label: 'Primary color'
    description: ''
    type: string
    default: 'rgb(210,222,50)'
  corporate.styles.colors.light:
    label: 'Logo Light color'
    description: ''
    type: string
    default: 'rgb(255,255 ,255)'
  corporate.styles.colors.dark:
    label: 'Dark color'
    description: ''
    type: string
    default: 'rgb(1,106,112)'
  corporate.social_media.text:
    label: 'Social media Text'
    description: 'Social media Text'
    type: string
    default: ''
  corporate.social_media.links.facebook:
    label: 'Facebook Page Link'
    description: 'Link of the Facebook page'
    type: string
    default: ''
  corporate.social_media.links.instagram:
    label: 'Instagram Page Link'
    description: 'Link of the Instagram page'
    type: string
    default: ''
  corporate.social_media.links.x:
    label: 'X Page Link'
    description: 'Link of the X page'
    type: string
    default: ''
  corporate.social_media.links.tiktok:
    label: 'TikTok Page Link'
    description: 'Link of the TikTok page'
    type: string
    default: ''
  corporate.social_media.links.linkedin:
    label: 'Linkedin Page Link'
    description: 'Link of the Linkedin page'
    type: string
    default: ''
  corporate.pages.footerPid:
    label: 'Footer Pid'
    description: 'page uid to display the footer'
    type: int
    default: 1
  corporate.product.showPid:
    label: 'Product Show Pid'
    description: 'Page who contains the product show plugin'
    type: int
    default: 2
  corporate.product.categoryRootUid:
    label: 'Category root uid for products'
    description: 'Sets the root uid for product categories'
    type: int
    default: 1
  corporate.product.contactFormPid:
    label: 'Pid of contact form'
    description: 'Shows a link to the contact form on the detail page'
    type: int
    default: 3
  corporate.content.footer.trademark:
    label: 'Trademark Text'
    description: 'trademark text that will appear on bottom of the pages'
    type: string
    default: ''
  corporate.content.information.text:
    label: 'Information Text'
    description: 'text that will appear on bottom of the footer'
    type: string
    default: ''
  corporate.content.information.email:
    label: 'Email Address'
    description: 'Main Contact Email address'
    type: string
    default: ''
  corporate.content.information.phone:
    label: 'Phone Number'
    description: 'Main Contact Phone Number'
    type: string
    default: ''
  corporate.content.information.address:
    label: 'Corporate Headquarter'
    description: 'Headquarter Address'
    type: string
    default: ''