#!/bin/bash

## #ddev-generated
## Description: Tail the main solr log
## Usage: typo3
## Example: ddev typo3

# This can't work unless you have a solr service,
# See https://ddev.readthedocs.io/en/stable/users/extend/additional-services/

ddev exec ./bin/typo3 $@