imports:
  - { resource: "../defaults.yaml" }

base: 'https://surfcamp-team1.ddev.site/'
dependencies:
  - surfcamp/corporate
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: ''
  -
    title: Deutsch
    enabled: true
    locale: de_DE.UTF-8
    hreflang: de_DE
    base: /de/
    websiteTitle: ''
    navigationTitle: Deutsch
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
rootPageId: 1
websiteTitle: ''